### ISSUE TITLE
部分博主链接失效

### ISSUE THREAD

**Issue by pujiaxin33** [awesome-tips/blogs#6]
点击时间2018-05-09 上午10：39
1、YY的微博
2、WeRead团队微博、github
3、李忠微博
4、swift talk 应该是没有微博的，但是有icon链接
5、Leo的微博
以上是我自测无效链接，还望确认一下。毕竟整理出来博主列表，但是链接无效，想必关注者会有些失落的。

**Comment by southpeak** [comment]
@pujiaxin33 ，感谢指正，问题都已修复哈，我们优化了一下生成脚本。由于都是利用业余时间收集，信息比较多，没有完全确认，后期我们会注意
